### ISSUE TITLE
Flick Demo worked once. After reboot it stopped working

### ISSUE THREAD

**Issue by RobertKrens** [PiSupply/Flick#62]
Good afternoon.

Using a RPI4 8GB and a Flick Large.

The "pip install flicklib" gives the following data:
```
pi@MagicMirror:~ $ sudo pip install flicklib
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: flicklib in /usr/local/lib/python2.7/dist-packages/flicklib-0.      0.3-py2.7.egg (0.0.3)
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (from flicklib) (      0.7.0)
```
So It seems the Flick Libary is up to date.

Running "i2cdetect -y -q 1" Shows:
```

`     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- 42 -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
`
```
Now I have a PIR sensor connected at GPIO21 (which works)
Also I've enabled I2C in the Raspi-Config

The Flick board powers up, but running the "pi@MagicMirror:~ $ ./flick-demo" command shows:

```
Did not receive firmware info
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-armv7l/egg/flicklib.py", line 468, in _exit
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-armv7l/egg/flicklib.py", line 468, in _exit
TypeError: 'NoneType' object is not callable
```

As I'm using a RPI4 8GB I've updated my WiringPi from 2.50 to 2.52 by this tutorial:
http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/ 
This made the Flick-Demo work once. However, Touch, Tab and double tab work. Flick, Airwheel, and XYZ wont give any readings. I tried a sudo reboot and now I'm back to my first problem: 
```
pi@MagicMirror:~ $ flick-demo
Did not receive firmware info
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-armv7l/egg/flicklib.py", line 468, in _exit
TypeError: 'NoneType' object is not callable
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "build/bdist.linux-armv7l/egg/flicklib.py", line 468, in _exit
TypeError: 'NoneType' object is not callable

```

I can still change the LED color by:
```
gpio -g mode 22 out
gpio -g write 22 1
```

Running a FlickBoard Firmware update shows:
```
can't open  gpio xfer direction file
can't open  pin file
can't open  gpio xfer direction file
can't open  gpio xfer direction file
can't open  pin file
 Loader record_count 109
 lib record_count 222
Flashing loader.
gestic_flash_begin
read error
ReceiveMsg

read error
read error
gestic_flash_write: success
gestic_flash_write: success
read error
gestic_flash_write: success
read error
gestic_flash_write: success
read error
and so on... 
```
This also once worked, but after "the sudo reboot" it doesn't work anymore. 

What am I missing? I anyone point me in a direction.

Thanks in advance,
Regards Robert

**Comment by RobertKrens** [comment]
Support call can be closed. Bought a new flick board, works perfect.

**Comment by danny7894** [comment]
How do you do a flickboard firmware update??
